### ISSUE TITLE
你好，我在尝试编译程序时，遇到一些问题，我查到是kendryte-standalone-sdk版本之间的冲突，请问你使用的哪个版本？

### ISSUE THREAD

**Issue by onearrow** [zp-jump/LFFD-LP-K210#1]

**Comment by zp-jump** [comment]
我刚刚进行了测试，可以使用最新的 develop 分支 SDK (6c3540600422257029c40e6c77b137d5a2c5d794) 进行编译，可以克隆 kendryte-standalone-sdk 进行编译。

**Comment by onearrow** [comment]
你使用的开发版是paddlePi吗？我使用的Sipeed maix板子和Arduino的环境。

**Comment by onearrow** [comment]
> 我刚刚进行了测试，可以使用最新的 develop 分支 SDK (6c3540600422257029c40e6c77b137d5a2c5d794) 进行编译，可以克隆 kendryte-standalone-sdk 进行编译。

**Comment by onearrow** [comment]
> 你使用的开发版是paddlePi吗？我使用的Sipeed maix板子和Arduino的环境。

**Comment by zp-jump** [comment]
我用的也是Maix 但是裸机编程
